### ISSUE TITLE
Python 3.7 error: AttributeError: 'code' object has no attribute 'replace'

### ISSUE THREAD

**Issue by SkeletalDemise** [Svenskithesource/PyArmor-Unpacker#17]
Python 3.7.13 32 bit.

```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "<string>", line 358, in <module>
  File "<string>", line 179, in output_code
  File "<string>", line 179, in <genexpr>
  File "<string>", line 191, in output_code
  File "<string>", line 213, in handle_armor_enter
AttributeError: 'code' object has no attribute 'replace'
```

**Comment by Svenskithesource** [comment]
This issue is because code.replace() was only introduced in 3.8 and higher, we can fix this by replacing the code.replace() with  copy_code_obj which is already included in the methods
