### ISSUE TITLE
KeyError: 'SETUP_FINALLY'

### ISSUE THREAD

**Issue by rn3r** [Svenskithesource/PyArmor-Unpacker#31]
Traceback (most recent call last):
  File "C:\Users\polsk\Desktop\unpyarmor\method_1.py", line 10, in <module>
    SETUP_FINALLY = opcode.opmap["SETUP_FINALLY"]
                    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'SETUP_FINALLY'

**Comment by Svenskithesource** [comment]
What Python version are you running?

**Comment by 0xdavidel** [comment]
I have it also, its on python 3.11

**Comment by Svenskithesource** [comment]
> I have it also, its on python 3.11

On Python 3.11 this opcode doesn't exist anymore. You can create an issue and hope someone will fix it, I might be able to but I'm very busy right now.

**Comment by kinetikFR** [comment]
:( AQUI ACONTECE A MESMA COSIA

**Comment by kinetikFR** [comment]
I have it also, its on python 3.11

**Comment by kinetikFR** [comment]
I have it also, its on python 3.11

**Comment by kinetikFR** [comment]
I have it also, its on python 3.11

**Comment by dranadkat** [comment]
File "C:\Users\vhind\Desktop\PyArmor-Unpacker-main\bypass.py", line 21, in <module>
    SETUP_FINALLY = opcode.opmap["SETUP_FINALLY"]
                    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'SETUP_FINALLY'

method 3
python .3.11
